#file: noinspection ComposeUnknownValues
# docker-compose.template.yml

# This is the base template for the PiSelfhosting Docker Compose setup.
# The piselfhosting_installer.py script will merge the selected component
# templates into this file to generate the final docker-compose.yml.

services:
  # Services will be dynamically added here by the installer.

networks:
  piselfhosting-network:
    driver: bridge