services:
  dashy:
    container_name: piselfhosting-dashy
    image: lissy93/dashy:{{ DASHY_IMAGE_TAG | default('latest') }}
    restart: unless-stopped
    ports:
      - "{{ DASHY_HTTP_PORT | default('8080') }}:80"
      - "{{ DASHY_HTTPS_PORT | default('4443') }}:443"
    volumes:
      - "{{ DATA_ROOT | default('/srv/piselfhosting') }}/dashy/conf.yml:/app/user-data/conf.yml"
    environment:
      - "PUID={{ PUID | default('1000') }}"
      - "PGID={{ PUID | default('1000') }}" # PGID uses the same as PUID
      - "TZ={{ TZ | default('Europe/Amsterdam') }}"
      - NODE_ENV=production
    extra_hosts:
      - "{{ DOMAIN | default('home.arpa') }}:{{ HOST_IP }}"
    networks:
      - piselfhosting_net
networks:
  piselfhosting_net:
    external: true