services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: piselfhosting-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - piselfhosting_net

networks:
  piselfhosting_net:
    external: true

