# Dovecot virtual users file
# Format: username:password_hash[:uid:gid:home:extra_fields]
# Use {SHA512-CRYPT} for SHA512 hashed passwords (recommended).
henk@henkenyvonnevanhoek.nl:$6$TT3O4uj5H5VFsjCU$nvy8NwK0U.uEhpdebeN7KcGBrRG6GLEeRGN2E0tM5u2XmM4ikefv3dFATsh3RfxjthxkM2yHsnVvgiokafLc5.
yvonne@henkenyvonnevanhoek.nl:$6$q8lIMKfnPb37g7v0$Pic52EJ..L4KMfxYmDTIZqaCvFnyXO.4bVBt2fVLHwbOxwhZFPXf/8242dSN0YDLTITFRP87PeCBatgcY8NYe1
