services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:{{ component_version }}
    container_name: piselfhosting-qbittorrent
    restart: unless-stopped
    environment:
      - "PUID={{PUID}}"
      - "PGID={{PGID}}"
      - "TZ={{TZ}}"
      - "WEBUI_PORT=8084"
    volumes:
      - "{{DATA_ROOT}}/qbittorrent/config:/config"
      # This is the central downloads folder that Sonarr/Radarr will also use
      - "{{DATA_ROOT}}/downloads:/downloads"
    ports:
      - "8084:8084"
      # Port for incoming torrent connections
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - piselfhosting_net

networks:
  piselfhosting_net:
    external: true
