#!/bin/bash
# PiSelfhosting Remove Component Script (Generated by deploy.sh)
# Location: ${SCRIPTS_DIR}/remove-component.sh # Escaped

# This script allows you to remove specific PiSelfhosting components.

# Stop the script if any command fails
set -e

BASE_DIR="/home/PiSelfhosting"
SCRIPTS_DIR="/home/PiSelfhosting/scripts"
ENV_FILE="/home/PiSelfhosting/.env"
COMPONENTS_FILE="/home/PiSelfhosting/scripts/selected_components.txt"
DOCKER_COMPOSE_DIR="/home/PiSelfhosting/docker"
MAIN_COMPOSE_FILE="/home/PiSelfhosting/docker-compose.yml"

# Load environment variables
echo "Info: Loading environment variables from $ENV_FILE and exporting them..."
if [ -f "$ENV_FILE" ]; then
    set -a
    source "$ENV_FILE"
    set +a
    echo "✅ Environment variables loaded."
fi

# Set the COMPOSE_PROJECT_NAME for consistent Docker Compose operations
export COMPOSE_PROJECT_NAME="piselfhosting"

DOCKER_COMPOSE_EXEC_CMD="docker compose"

if [ -z "$DOCKER_COMPOSE_EXEC_CMD" ]; then
    echo "❌ Docker Compose not found. Cannot remove components."
    exit 1
fi

echo "--- Remove PiSelfhosting Component ---"

if [ ! -f "${COMPONENTS_FILE}" ]; then # ESCAPE
    echo "❌ Error: selected_components.txt not found at ${COMPONENTS_FILE}. No components to remove." # ESCAPE
    exit 1
fi

read -r -a SELECTED_COMPONENTS <<< "$(cat "${COMPONENTS_FILE}" | tr -d '"')" # ESCAPE
if [ ${#SELECTED_COMPONENTS[@]} -eq 0 ]; then
    echo "Info: No components are currently selected/installed. Nothing to remove."
    exit 0
fi

# whiptail requires local scope for options to prevent issues with variable expansion inside loops
declare -a remove_options=()
for comp in "${SELECTED_COMPONENTS[@]}"; do
    remove_options+=("$comp" "" "OFF")
done

if [ ${#remove_options[@]} -gt 0 ]; then
    REMOVE_CHOICES=$(whiptail --title "Remove PiSelfhosting Component" --checklist     "Choose components to remove (use space to select/deselect, Enter to confirm):" 20 78 10     "${remove_options[@]}" 3>&1 1>&2 2>&3)

    if [ $? -ne 0 ]; then
        echo "Component removal canceled."
        exit 0
    fi
else
    echo "Info: No removable components found."
    exit 0
fi

# Convert chosen components to an array
declare -a COMPONENTS_TO_REMOVE=()
if [ -n "$REMOVE_CHOICES" ]; then
    # Remove quotes and split by spaces
    COMPONENTS_TO_REMOVE=($(echo "$REMOVE_CHOICES" | tr -d '"'))
fi

if [ ${#COMPONENTS_TO_REMOVE[@]} -eq 0 ]; then
    echo "No components selected for removal."
    exit 0
fi

echo "--- Removing selected components ---"

declare -a new_selected_components=()
for comp in "${SELECTED_COMPONENTS[@]}"; do
    local found_to_remove=false # Keep local for this inner loop var
    for to_remove in "${COMPONENTS_TO_REMOVE[@]}"; do
        if [ "$comp" == "$to_remove" ]; then
            found_to_remove=true
            echo "Stopping and removing container for '$comp'..."
            if ${DOCKER_COMPOSE_EXEC_CMD} -f "$MAIN_COMPOSE_FILE" rm -s -v -f "$comp"; then # -s for stop, -v for volumes, -f for force
                echo "✅ Container and associated volumes for '$comp' removed."
            else
                echo "⚠️ Failed to remove container/volumes for '$comp'. Manual cleanup might be needed."
            fi
            # Remove its docker-compose.yml and config directory
            if [ -d "/home/PiSelfhosting/docker/$comp" ]; then
                echo "Removing component directory: /home/PiSelfhosting/docker/$comp"
                sudo rm -rf "/home/PiSelfhosting/docker/$comp"
            fi
            break
        fi
    done
    if [ "$found_to_remove" = false ]; then
        new_selected_components+=("$comp")
    fi
done

# Update selected_components.txt
printf '"%s" ' "${new_selected_components[@]}" > "${COMPONENTS_FILE}" # ESCAPE
echo "✅ selected_components.txt updated."

echo -e "\n--- Component removal complete ---"
echo "You may need to run 'docker system prune' to clean up unused Docker resources."
