#!/bin/bash
# PiSelfhosting Stop All Script (Generated by deploy.sh)
# Location: ${SCRIPTS_DIR}/stop-all.sh # Escaped

# Stop the script if a command fails
set -e

BASE_DIR="/home/PiSelfhosting"
ENV_FILE="/home/PiSelfhosting/.env"

# Load environment variables
echo "Info: Loading environment variables from $ENV_FILE and exporting them..."
if [ -f "$ENV_FILE" ]; then
    set -a
    source "$ENV_FILE"
    set +a
    echo "✅ Environment variables loaded."
else
    echo "❌ Error: .env file not found at $ENV_FILE. Cannot stop services."
    exit 1
fi

# Set the COMPOSE_PROJECT_NAME for consistent Docker Compose operations
export COMPOSE_PROJECT_NAME="piselfhosting"

DOCKER_COMPOSE_EXEC_CMD="docker compose"

echo "🛑 Stopping all PiSelfhosting containers..."
MAIN_COMPOSE_FILE="/home/PiSelfhosting/docker-compose.yml"
if [ -f "$MAIN_COMPOSE_FILE" ]; then
    echo "Info: Running 'docker compose down --volumes --remove-orphans' on the unified docker-compose.yml..."
    (cd "$BASE_DIR" && ${DOCKER_COMPOSE_EXEC_CMD} -f "$MAIN_COMPOSE_FILE" down) || {
        echo "⚠️ Failed to stop some services. Check logs."
    }
else
    echo "Warning: docker-compose.yml not found at $MAIN_COMPOSE_FILE. Cannot stop services."
fi
echo "✅ All selected containers stopped."
