#!/bin/bash
# PiSelfhosting Restart All Script (Generated by deploy.sh)
# Location: /home/PiSelfhosting/scripts/restart-all.sh

BASE_DIR="/home/PiSelfhosting"
SCRIPTS_DIR="\$BASE_DIR/scripts"

echo "🔄 Restarting all PiSelfhosting services..."
"\$SCRIPTS_DIR/stop-all.sh" "\$@"
"\$SCRIPTS_DIR/start-all.sh" "\$@"
echo "✅ Restart complete."
