#!/bin/bash
# PiSelfhosting Restart All Script (Generated by deploy.sh)
# Location: ${SCRIPTS_DIR}/restart-all.sh # Escaped

BASE_DIR="/home/PiSelfhosting"
SCRIPTS_DIR="/home/PiSelfhosting/scripts"

echo "🔄 Restarting all PiSelfhosting services..."
"$SCRIPTS_DIR/stop-all.sh" "$@"
"$SCRIPTS_DIR/start-all.sh" "$@"
echo "✅ Restart complete."
