#!/bin/bash
# PiSelfhosting Start All Script (Generated by deploy.sh)
# Location: ${SCRIPTS_DIR}/start-all.sh # Escaped for later interpretation

# Stop the script if a command fails
set -e

BASE_DIR="/home/PiSelfhosting"
ENV_FILE="/home/PiSelfhosting/.env"
NETWORK_NAME="piselfhosting_net"

# --- Load environment variables ---
echo "Info: Loading environment variables from $ENV_FILE and exporting them..."
if [ -f "$ENV_FILE" ]; then
    set -a # Automatically export all subsequent assignments
    source "$ENV_FILE"
    set +a # Disable auto-export
    echo "✅ Environment variables loaded."
else
    echo "❌ Error: .env file not found at $ENV_FILE. Please run setup.sh first."
    exit 1
fi

# --- Create Docker network if it doesn't exist ---
if ! docker network inspect "$NETWORK_NAME" &>/dev/null; then
    echo "Info: Docker network '$NETWORK_NAME' not found. Creating..."
    docker network create "$NETWORK_NAME"
    echo "✅ Docker network '$NETWORK_NAME' created."
else
    echo "Info: Docker network '$NETWORK_NAME' already exists."
fi

echo "🚀 Starting PiSelfhosting containers in dependency order..."

# --- Ensure a clean start by stopping and removing existing containers ---
echo "Attempting to stop and remove any existing PiSelfhosting containers for a clean start..."

# Explicitly stop and remove the mosquitto container first, in case it's lingering
# from a manual run or a different project context.
MOSQUITTO_CONTAINER_NAME="piselfhosting-mosquitto"
if docker ps -a --format '{{.Names}}' | grep -q "^${MOSQUITTO_CONTAINER_NAME}$"; then
    echo "Info: Found existing '$MOSQUITTO_CONTAINER_NAME'. Stopping and removing..."
    docker stop "$MOSQUITTO_CONTAINER_NAME" &>/dev/null || true
    docker rm "$MOSQUITTO_CONTAINER_NAME" &>/dev/null || true
    echo "✅ '$MOSQUITTO_CONTAINER_NAME' removed."
fi

# Set the COMPOSE_PROJECT_NAME for consistent Docker Compose operations
export COMPOSE_PROJECT_NAME="piselfhosting"

DOCKER_COMPOSE_EXEC_CMD="docker compose"

# Use docker compose down to stop and remove services managed by this project
# --remove-orphans ensures any containers that are no longer defined in the compose file
# but were part of the project are also removed.
MAIN_COMPOSE_FILE="/home/PiSelfhosting/docker-compose.yml"
if [ -f "$MAIN_COMPOSE_FILE" ]; then
    echo "Info: Running 'docker compose down --volumes --remove-orphans' on the unified docker-compose.yml..."
    (cd "$BASE_DIR" && ${DOCKER_COMPOSE_EXEC_CMD} -f "$MAIN_COMPOSE_FILE" down --volumes --remove-orphans) || {
        echo "⚠️ Could not cleanly bring down the unified project. Some containers/volumes might remain."
    }
else
    echo "Warning: docker-compose.yml not found at $MAIN_COMPOSE_FILE. Cannot perform clean shutdown of compose services."
fi

# --- Read selected components for starting ---
COMPONENTS_FILE="/home/PiSelfhosting/scripts/selected_components.txt" # This variable is already outside the problem section
if [ ! -f "${COMPONENTS_FILE}" ]; then # ESCAPE
    echo "❌ Error: selected_components.txt not found at ${COMPONENTS_FILE}. Please run setup.sh first." # ESCAPE
    exit 1
fi

read -r -a SELECTED_COMPONENTS_ARRAY <<< "$(cat "${COMPONENTS_FILE}" | tr -d '"')" # ESCAPE
if [ ${#SELECTED_COMPONENTS_ARRAY[@]} -eq 0 ]; then
    echo "Info: No components selected in ${COMPONENTS_FILE}. Nothing to start." # ESCAPE
    exit 0
fi

# Translate selected component names to service names (e.g., component_name -> docker-compose_service_name)
declare -a SERVICES_TO_START_ARGS=()
for comp_name in "${SELECTED_COMPONENTS_ARRAY[@]}"; do
    SERVICES_TO_START_ARGS+=("$comp_name")
done

echo "Starting all selected services as a single Docker Compose project..."
if ${DOCKER_COMPOSE_EXEC_CMD} -f "$MAIN_COMPOSE_FILE" up -d --build --remove-orphans ${SERVICES_TO_START_ARGS[*]}; then
    echo "✅ All selected PiSelfhosting containers started successfully."
    echo -e "\n--- PiSelfhosting Services Started ---"
    echo "You can check the status of your containers with: docker ps"
    echo "Or view logs with: ${DOCKER_COMPOSE_EXEC_CMD} logs -f"
    echo "If you selected Portainer, you can access its UI (usually on port 9000 or a subdomain)."
    echo "Access your services via the domain you set during setup (e.g., Dashy at dashboard.$DOMAIN)."
else
    echo "❌ Failed to start one or more services. Check Docker logs for details."
    exit 1
fi
