#!/bin/bash
# PiSelfhosting Stop All Script (Generated by deploy.sh)
# Location: /home/PiSelfhosting/scripts/stop-all.sh

# Stop the script if a command fails
set -e

BASE_DIR="/home/PiSelfhosting"
ENV_FILE="\$BASE_DIR/.env"

# Load environment variables
if [ -f "\$ENV_FILE" ]; then
    set -a
    source "\$ENV_FILE"
    set +a
fi

# Set the COMPOSE_PROJECT_NAME for consistent Docker Compose operations
export COMPOSE_PROJECT_NAME="piselfhosting"

DOCKER_COMPOSE_COMMAND_PATH="\$BASE_DIR/scripts/get_docker_compose_cmd.sh"
DOCKER_COMPOSE_EXEC_CMD=\$("\$DOCKER_COMPOSE_COMMAND_PATH")

echo "🛑 Stopping all PiSelfhosting containers..."
MAIN_COMPOSE_FILE="\$BASE_DIR/docker-compose.yml"
if [ -f "\$MAIN_COMPOSE_FILE" ]; then
    (cd "\$BASE_DIR" && \${DOCKER_COMPOSE_EXEC_CMD} -f "\$MAIN_COMPOSE_FILE" down) || {
        echo "⚠️ Failed to stop some services. Check logs."
    }
else
    echo "Warning: docker-compose.yml not found at \$MAIN_COMPOSE_FILE. Cannot stop services."
fi
echo "✅ All selected containers stopped."
