#!/bin/bash
# PiSelfhosting Start All Script (Generated by deploy.sh)
# Location: /home/PiSelfhosting/scripts/start-all.sh

# Stop the script if a command fails
set -e

BASE_DIR="/home/PiSelfhosting"
echo "DEBUG: \$BASEDIR:" $BASE_DIR
ENV_FILE="\$BASE_DIR/.env"
echo "DEBUG: \$ENV_FILE: " $ENV_FILE

ENV_FILE=$BASE_DIR"/.env"

echo "DEBUG: \$ENV_FILE: " $ENV_FILE

NETWORK_NAME="piselfhosting_net" # Use the NETWORK_NAME variable from deploy.sh

# --- Load environment variables ---
echo "Info: Loading environment variables from \$ENV_FILE and exporting them..."
if [ -f "$ENV_FILE" ]; then
    set -a # Automatically export all subsequent assignments
    source "$ENV_FILE"
    set +a # Disable auto-export
    echo "✅ Environment variables loaded."
else
    echo "❌ Error: .env file not found at \$ENV_FILE. Please run setup.sh first."
    exit 1
fi
echo "DEBUG: After loading environment variables."
