services:
  portainer:
    image: portainer/portainer-ce:{{ PORTAINER_IMAGE_TAG | default('lts') }}
    container_name: piselfhosting-portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "{{ PORTAINER_HTTPS_PORT | default('9443') }}:9443"
      - "{{ PORTAINER_EDGE_PORT | default('8000') }}:8000"
    networks:
      - piselfhosting_net

volumes:
  portainer_data:
    name: piselfhosting-portainer-data

networks:
  piselfhosting_net:
    external: true
