---
- name: Deploy PiSelfhosting Services
  hosts: all
  become: true
  vars:
    # Destination path on the Pi for all configuration
    project_config_dir: "/opt/piselfhosting"

  tasks:
    - name: Pre flight check Ensure at least 2GB of free disk space is available
      ansible.builtin.assert:
        that:
          - item.size_available > 2147483648  # 2 GB in bytes
        fail_msg: >-
          Deployment aborted: The Pi does not have enough free disk space on
          {{ item.mount }}. Please clean up the device.
        success_msg: "Disk space check passed on {{ item.mount }}."
      loop: "{{ ansible_mounts }}"
      when: item.mount == '/'

    - name: Ensure project directory exists
      ansible.builtin.file:
        path: "{{ project_config_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Copy all deployment files to the Pi (including .env and config folders)
      ansible.builtin.copy:
        # trailing slash is required to copy the content of the folder (/)
        src: "{{ local_output_path }}/"
        dest: "{{ project_config_dir }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "preserve"

    - name: Perform Clean Install (Stop containers and remove volumes for selected components)
      ansible.builtin.command:
        cmd: "docker compose rm -f -s -v {{ item }}"
        chdir: "{{ project_config_dir }}"
      loop: "{{ components_to_clean | default([]) }}"
      when: components_to_clean is defined and components_to_clean | length > 0
      changed_when: true

    - name: Ensure PiSelfhosting Docker network exists
      community.docker.docker_network:
        name: piselfhosting_net
        state: present
        driver: bridge

    - name: Deploy services with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ project_config_dir }}"
        state: present
        pull: always

    - name: Restart specifically requested components
      ansible.builtin.command:
        cmd: "docker compose restart {{ item }}"
        chdir: "{{ project_config_dir }}"
      loop: "{{ components_to_restart | default([]) }}"
      when: components_to_restart is defined and components_to_restart | length > 0
      changed_when: true
