pageInfo:
  title: PiSelfhosting Dashboard
  description: Overview of your self-hosted services
  navLinks:
  - title: GitHub
    path: https://github.com/your-username/your-repo
  - title: Docs
    path: https://dashy.to/docs/
  footerText: Powered by Dashy
appConfig:
  theme: material
  layout: auto
  iconSize: medium
  language: en
sections:
- name: General Services
  icon: fa-solid fa-server
  items:
  - title: Docker Monitor (Simple Docker Stats Page)
    description: Docker Monitor (Simple Docker Stats Page)
    icon: fas fa-chart-line
    url: http://"mail.henkenyvonne.nl":8088
    statusCheck: true
