name: Build macOS Installer

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller (macOS)
        run: >-
          python -m PyInstaller --onefile
          --name "PiSelfhosting-Installer-macOS"
          --icon="piselfhosting-apple.icns"
          --add-data "src:src"
          --add-data "favicon
          --add-data "templates:templates"
          --add-data "components_list.txt:."
          --add-data "config:config"
          --add-data "config/default_selected_components.txt:selected_components.txt"
          --add-data "Dockerfile.setup-tool:."
          piselfhosting_installer.py

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/PiSelfhosting-Installer-macOS
          asset_name: PiSelfhosting-Installer-macOS
          asset_content_type: application/octet-stream
          tag: ${{ github.ref_name }}
          overwrite: true